#-*- encoding: utf-8 -*-
"""
Pentagon numbers

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""

from utils import *

pentagonal = lambda n: n * (3 * n - 1) / 2
is_pentagonal = lambda n: (lambda s: s * (3 * s - 1) == n * 2)(
    int((n * 2.0 / 3) ** 0.5) + 1)
ps = set(pentagonal(n) for n in range(1, 3000))
print min(p1 - p2 for p1 in ps for p2 in ps if p1 + p2 in ps and p1 - p2 in ps)
# 5482660
