#-*- encoding: utf-8 -*-
"""
Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle    Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal  Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
Hexagonal   Hn=n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
"""

from utils import *

triangle = lambda n: (lambda s: s * (s + 1) == n * 2)(int((n * 2) ** 0.5))
hexagonal = lambda n: (lambda s: s * (2 * s - 1) == n)(int((n / 2) ** 0.5) + 1)
i = 166
while 1:
    pentagonal = i * (3 * i - 1) / 2
    if triangle(pentagonal) and hexagonal(pentagonal):
        print pentagonal
        break
    i += 1
# 1533776805
